### ISSUE TITLE
Add config to setup.py

### ISSUE THREAD

**Issue by CommanderRedYT** [UserBlackBox/octoprint-cli#15]
**Describe the solution you'd like**
Use idk input() to ask user for settings in the setup.py script

**Describe alternatives you've considered**
 - Open the config.ini file in vim or nano after install has finished
 - Print out path from config file

**Additional context**
Need this because I can't find the directory (htop always shows .local/bin/octoprint-cli, but idk where the config.ini would be)

**Comment by UserBlackBox** [comment]
`setup.py` isn't an installation script. It's a script for packaging and distributing the program. `pip` should be used instead of installing with `setup.py`. Configuration instructions can be found in the [readme](https://github.com/UserBlackBox/octoprint-cli#configuration) and the config file should be made yourself. An example of `config.ini` is available [here](https://github.com/UserBlackBox/octoprint-cli/blob/master/sample-config.ini)
